/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedGroupsRouteImport } from './routes/_authed/groups'
import { Route as AuthedDatabasesIndexRouteImport } from './routes/_authed/databases.index'
import { Route as AuthedDatabasesIdRouteImport } from './routes/_authed/databases.$id'
import { Route as AuthedAdminUsersRouteImport } from './routes/_authed/admin.users'
import { Route as AuthedAdminGrantsRouteImport } from './routes/_authed/admin.grants'
import { Route as AuthedAdminBackupsRouteImport } from './routes/_authed/admin.backups'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsRoute = AuthedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDatabasesIndexRoute = AuthedDatabasesIndexRouteImport.update({
  id: '/databases/',
  path: '/databases/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDatabasesIdRoute = AuthedDatabasesIdRouteImport.update({
  id: '/databases/$id',
  path: '/databases/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminUsersRoute = AuthedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminGrantsRoute = AuthedAdminGrantsRouteImport.update({
  id: '/admin/grants',
  path: '/admin/grants',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminBackupsRoute = AuthedAdminBackupsRouteImport.update({
  id: '/admin/backups',
  path: '/admin/backups',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/groups': typeof AuthedGroupsRoute
  '/admin/backups': typeof AuthedAdminBackupsRoute
  '/admin/grants': typeof AuthedAdminGrantsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/databases/$id': typeof AuthedDatabasesIdRoute
  '/databases/': typeof AuthedDatabasesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/groups': typeof AuthedGroupsRoute
  '/': typeof AuthedIndexRoute
  '/admin/backups': typeof AuthedAdminBackupsRoute
  '/admin/grants': typeof AuthedAdminGrantsRoute
  '/admin/users': typeof AuthedAdminUsersRoute
  '/databases/$id': typeof AuthedDatabasesIdRoute
  '/databases': typeof AuthedDatabasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/groups': typeof AuthedGroupsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/backups': typeof AuthedAdminBackupsRoute
  '/_authed/admin/grants': typeof AuthedAdminGrantsRoute
  '/_authed/admin/users': typeof AuthedAdminUsersRoute
  '/_authed/databases/$id': typeof AuthedDatabasesIdRoute
  '/_authed/databases/': typeof AuthedDatabasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/groups'
    | '/admin/backups'
    | '/admin/grants'
    | '/admin/users'
    | '/databases/$id'
    | '/databases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/groups'
    | '/'
    | '/admin/backups'
    | '/admin/grants'
    | '/admin/users'
    | '/databases/$id'
    | '/databases'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/groups'
    | '/_authed/'
    | '/_authed/admin/backups'
    | '/_authed/admin/grants'
    | '/_authed/admin/users'
    | '/_authed/databases/$id'
    | '/_authed/databases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups': {
      id: '/_authed/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthedGroupsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/databases/': {
      id: '/_authed/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof AuthedDatabasesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/databases/$id': {
      id: '/_authed/databases/$id'
      path: '/databases/$id'
      fullPath: '/databases/$id'
      preLoaderRoute: typeof AuthedDatabasesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/users': {
      id: '/_authed/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthedAdminUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/grants': {
      id: '/_authed/admin/grants'
      path: '/admin/grants'
      fullPath: '/admin/grants'
      preLoaderRoute: typeof AuthedAdminGrantsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/backups': {
      id: '/_authed/admin/backups'
      path: '/admin/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AuthedAdminBackupsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedGroupsRoute: typeof AuthedGroupsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAdminBackupsRoute: typeof AuthedAdminBackupsRoute
  AuthedAdminGrantsRoute: typeof AuthedAdminGrantsRoute
  AuthedAdminUsersRoute: typeof AuthedAdminUsersRoute
  AuthedDatabasesIdRoute: typeof AuthedDatabasesIdRoute
  AuthedDatabasesIndexRoute: typeof AuthedDatabasesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedGroupsRoute: AuthedGroupsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAdminBackupsRoute: AuthedAdminBackupsRoute,
  AuthedAdminGrantsRoute: AuthedAdminGrantsRoute,
  AuthedAdminUsersRoute: AuthedAdminUsersRoute,
  AuthedDatabasesIdRoute: AuthedDatabasesIdRoute,
  AuthedDatabasesIndexRoute: AuthedDatabasesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
